apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: paw-proxy
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  replicas:
    min: 2
    max: 2
  azure:
    application:
      enabled: true
  tokenx:
    enabled: true
  webproxy: true
  secureLogs:
    enabled: true
  ingresses:
    - "https://paw-proxy.dev-fss-pub.nais.io"
    - "https://paw-proxy.dev.intern.nav.no/"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: dev.nav.no
    - name: VEILARBREGISTRERING_URL
      value: http://veilarbregistrering
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.pto.svc.nais.local
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.pto.svc.nais.local
    - name: VEILARBVEILEDER_URL
      value: http://veilarbveileder.pto.svc.nais.local
    - name: ARENA_ORDS_URL
      value: https://arena-ords-readonly-q1.dev.intern.nav.no
    - name: ARENA_ORDS_TOKEN_URL
      value: https://arena-ords-q1.dev.intern.nav.no
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: "500m"
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering-veileder
          cluster: dev-gcp
          namespace: paw
        - application: dp-soknadsdialog
          cluster: dev-gcp
          namespace: teamdagpenger
        - application: veilarbregistrering
          cluster: dev-fss
          namespace: paw
        - application: veilarbregistrering
          cluster: dev-gcp
          namespace: paw
    outbound:
      rules:
        - application: veilarbregistrering
        - application: veilarboppfolging
          namespace: pto
        - application: veilarbperson
          namespace: pto
        - application: veilarbveileder
          namespace: pto
