apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: paw-proxy
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 2
  azure:
    application:
      enabled: true
  webproxy: true
  secureLogs:
    enabled: true
  ingresses:
    - "https://paw-proxy.dev-fsspub.nais.io"
    - "https://paw-proxy.dev.intern.nav.no/"
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: dev.nav.no
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: "500m"
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering-veileder
          cluster: dev-gcp
          namespace: paw
    outbound:
      rules:
        - application: veilarbregistrering
