apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: paw-proxy
  namespace: paw
  labels:
    team: paw
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  azure:
    application:
      enabled: true
      allowAllUsers: true
  tokenx:
    enabled: true
  webproxy: true
  secureLogs:
    enabled: true
  ingresses:
    - "https://paw-proxy.prod-fss-pub.nais.io"
    - "https://paw-proxy.intern.nav.no/"
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: nav.no
    - name: VEILARBOPPFOLGING_URL
      value: http://veilarboppfolging.pto.svc.nais.local
    - name: VEILARBPERSON_URL
      value: http://veilarbperson.pto.svc.nais.local
    - name: VEILARBVEILEDER_URL
      value: http://veilarbveileder.pto.svc.nais.local
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 256Mi
  accessPolicy:
    inbound:
      rules:
        - application: arbeidssokerregistrering-for-veileder
          cluster: prod-gcp
          namespace: paw
        - application: dp-soknadsdialog
          cluster: prod-gcp
          namespace: teamdagpenger
        - application: veilarbregistrering
          cluster: prod-gcp
          namespace: paw
        - application: paw-reaktiver-arbeidssoker
          cluster: prod-gcp
          namespace: paw
    outbound:
      rules:
        - application: veilarboppfolging
          namespace: poao
          cluster: prod-gcp
        - application: veilarbperson
          namespace: pto
        - application: veilarbveileder
          namespace: pto
